apiVersion: v1 
kind: Pod

metadata: 
  name: all-pods-reso
  labels:
    app: expense
    tier: backend
  annotations:
    kubernetes.io/created-by: kedar 
    jenkins.build.url: "http://78skedar.com/expense/job/backend/98"
spec:
  containers: 
    - name: nginx
      image: nginx
      ports: 
        - containerPort: 80
      env:
        - key: user 
          value: kedar
        - key: password
          value: hello
        
      resources:
        requests: 
          memory: "64Mi"
          cpu: "100m"
        limits: 
          memory: "64Mi"
          cpu: "100m"
        
