apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    environment: web 
    project: expense
    tier: frontend
    
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80